.TH geh 1 ""
.ds n 5
.SH NAME
\fBgeh\fR - command line image viewer for X
.br
.SH DESCRIPTION
\fBgeh\fR is a simple commandline image viewer written in C/Gtk+ with
various nice features. It currently supports the following modes:

    * Slide-show mode displaying multiple images in a row either
      controlled by an time interval and/or mousebutton clicks.
    * Thumbnail mode creating small thumbnail images and caching them
      i ~/.thumbnails according to freedesktop.org's thumbnail
      specification.
.PP
.SH SEE ALSO
For more information check out the geh project page at:
https://projects.pekdon.net/projects/geh
